# Python for Statistical Analysis ( Numpy )
### By : Eng.Amjaad Altakhaineh

## Statistics

Statistics is the discipline that studies the collection, organization, displaying, analysing, interpretation and presentation of data. Statistics is a branch of Mathematics that is recommended to be a prerequisite for data science and machine learning. Statistics is a very broad field but we will focus in this section only on the most relevant part. After completing this challenge, you may go onto the web development, data analysis, machine learning and data science path. Whatever path you may follow, at some point in your career you will get data which you may work on. Having some statistical knowledge will help you to make decisions based on data, data tells as they say.

## Data
What is data? Data is any set of characters that is gathered and translated for some purpose, usually analysis. It can be any character, including text and numbers, pictures, sound, or video. If data is not put in a context, it doesn't make any sense to a human or computer. To make sense from data we need to work on the data using different tools.

The work flow of data analysis, data science or machine learning starts from data. Data can be provided from some data source or it can be created. There are structured and unstructured data.

Data can be found in small or big format. Most of the data types we will get have been covered in the file handling section.

## Statistics Module

The Python statistics module provides functions for calculating mathematical statistics of numerical data. The module is not intended to be a competitor to third-party libraries such as NumPy, SciPy, or proprietary full-featured statistics packages aimed at professional statisticians such as Minitab, SAS and Matlab. It is aimed at the level of graphing and scientific calculators.

# NumPy

In the first section we defined Python as a great general-purpose programming language on its own, but with the help of other popular libraries as(numpy, scipy, matplotlib, pandas etc) it becomes a powerful environment for scientific computing.

NumPy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with arrays.

### Importing int numpy arrays


In [1]:
# Import Numpy based on thr Python version (3.12.7) Using Visiual studio IDE U can also use Spyder or any Jypoter 
import numpy as np

## Creating int numpy arrays


In [2]:
# Creating python List
python_list = [1,2,3,4,5]

# Checking data types
print('Type:', type (python_list)) # <class 'list'>

print(python_list) # [1, 2, 3, 4, 5]

two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]

print(two_dimensional_list)  # [[0, 1, 2], [3, 4, 5], [6, 7, 8]]



Type: <class 'list'>
[1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [2]:
# Tradational method (just storage and create)

import array
L=list(range(10))

A=array.array("i",L)

print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [9]:
# Creating Numpy(Numerical Python) array from python list 

numpy_array_from_list = np.array([1,4,2,5,3])
print(type (numpy_array_from_list))   # <class 'numpy.ndarray'>
print(numpy_array_from_list) # array([1, 2, 3, 4, 5])

<class 'numpy.ndarray'>
[1 4 2 5 3]


Remember that unlike Python lists, NumPy arrays can only contain data of the same type. If the types do not match, NumPy will upcast them according to its type promo‐ tion rules; here, integers are upcast to floating point:

In [10]:
numpy_array_from_list = np.array([1.33,4,2,5,3]) 

print(numpy_array_from_list) # the last numbers follow the same first number's type 

[1.33 4.   2.   5.   3.  ]


## Creating float numpy arrays
Creating a float numpy array from list with a float data type parameter

In [11]:
# Python list
python_list = [1,2,3,4,5]

numy_array_from_list2 = np.array(python_list, dtype=float)
print(numy_array_from_list2) # array([1., 2., 3., 4., 5.])

[1. 2. 3. 4. 5.]


If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:

In [13]:
a=np.array([1, 2, 3, 4], dtype=np.float32)

print(a)

[1. 2. 3. 4.]


## Creating boolean numpy arrays
Creating a boolean a numpy array from list


   

In [14]:
numpy_bool_array = np.array([0, 1, -1, 0, 0], dtype=bool)
print(numpy_bool_array) # array([False,  True,  True, False, False])

[False  True  True False False]


    
## Creating multidimensional array using numpy
A numpy array may have one or multiple rows and columns


In [15]:
two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]
numpy_two_dimensional_list = np.array(two_dimensional_list)
print(type (numpy_two_dimensional_list))
print(numpy_two_dimensional_list)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Converting numpy array to list


In [18]:
# We can always convert an array back to a python list using tolist().
two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]
numpy_two_dimensional_list = np.array(two_dimensional_list)
np_to_list = numpy_array_from_list.tolist()
print(type (np_to_list))
print('one dimensional array:', np_to_list)
print('two dimensional array: ', numpy_two_dimensional_list.tolist())

<class 'list'>
one dimensional array: [1.33, 4.0, 2.0, 5.0, 3.0]
two dimensional array:  [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [19]:
# arang 

np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [20]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

## Creating numpy array from tuple

In [ ]:
# Numpy array from tuple
# Creating tuple in Python
python_tuple = (1,2,3,4,5)
print(type (python_tuple)) # <class 'tuple'>
print('python_tuple: ', python_tuple) # python_tuple:  (1, 2, 3, 4, 5)

numpy_array_from_tuple = np.array(python_tuple)
print(type (numpy_array_from_tuple)) # <class 'numpy.ndarray'>
print('numpy_array_from_tuple: ', numpy_array_from_tuple) # numpy_array_from_tuple:  [1 2 3 4 5]

## Shape of numpy array

The shape method provide the shape of the array as a tuple. The first is the row and the second is the column. If the array is just one dimensional it returns the size of the array.

In [ ]:
nums = np.array([1, 2, 3, 4, 5])
print(nums)
print('shape of nums: ', nums.shape)
print(numpy_two_dimensional_list)
print('shape of numpy_two_dimensional_list: ', numpy_two_dimensional_list.shape)
three_by_four_array = np.array([[0, 1, 2, 3],
        [4,5,6,7],
        [8,9,10, 11]])
print(three_by_four_array.shape)

## Data type of numpy array

Type of data types: str, int, float, complex, bool, list, None

In [4]:
int_lists = [-3, -2, -1, 0, 1, 2,3]
int_array = np.array(int_lists)
float_array = np.array(int_lists, dtype=float)

print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)

[-3 -2 -1  0  1  2  3]
int64
[-3. -2. -1.  0.  1.  2.  3.]
float64


## Size of a numpy array

In numpy to know the number of items in a numpy array list we use size

In [3]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
two_dimensional_list = np.array([[0, 1, 2],
                              [3, 4, 5],
                              [6, 7, 8]])

print('The size:', numpy_array_from_list.size) # 5
print('The size:', two_dimensional_list.size)  # 3


The size: 5
The size: 9


## Mathematical Operation using numpy
---------
NumPy array is not like exactly like python list. To do mathematical operation in Python list we have to loop through the items but numpy can allow to do any mathematical operation without looping. Mathematical Operation:

* Addition (+)
* Subtraction (-)
* Multiplication (*)
* Division (/)
* Modules (%)
* Floor Division(//)
* Exponential(**)

## Addition



In [ ]:
# Mathematical and concatenation Operations


# Addition
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_plus_original = numpy_array_from_list  + 10
print(ten_plus_original)



# concatenate 
'''But if u want to join multi-array use concatenate function #### ''' 
var1 = ([1,2,3,4,5])
var2 = ([6,7,8,9,10])
ar = np.concatenate((var1,var2))
print(ar)


## Subtraction

 

In [ ]:
# Subtraction
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_minus_original = numpy_array_from_list  - 10
print(ten_minus_original) 

## Multiplication



In [ ]:
# Multiplication
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list * 10
print(ten_times_original)

## Division



In [ ]:
# Division
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list / 10
print(ten_times_original)

## Modulus

In [ ]:
# Modulus; Finding the remainder
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list % 3
print(ten_times_original)

## Floor Division



In [ ]:
# Floor division: the division result without the remainder
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list // 10
print(ten_times_original)

## Exponential



In [ ]:
# Exponential is finding some number the power of another:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list  ** 2
print(ten_times_original)

## Checking data types



In [5]:
#Int,  Float numbers
numpy_int_arr = np.array([1,2,3,4])
numpy_float_arr = np.array([1.1, 2.0,3.2])
numpy_bool_arr = np.array([-3, -2, 0, 1,2,3], dtype='bool')

print(numpy_int_arr.dtype)
print(numpy_float_arr.dtype)
print(numpy_bool_arr.dtype)

int64
float64
bool


## Converting types

We can convert the data types of numpy array

1. Int to Float

In [ ]:
numpy_int_arr = np.array([1,2,3,4], dtype = 'float')
numpy_int_arr

2. Float to Int


In [ ]:
numpy_int_arr = np.array([1., 2., 3., 4.], dtype = 'int')
numpy_int_arr

3. Int ot boolean


In [ ]:
np.array([-3, -2, 0, 1,2,3], dtype='bool')


4. Int to str


## Multi-dimensional Arrays



In [ ]:
# 2 Dimension Array
two_dimension_array = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(type (two_dimension_array))
print(two_dimension_array)
print('Shape: ', two_dimension_array.shape)
print('Size:', two_dimension_array.size)
print('Data type:', two_dimension_array.dtype)

## Getting items from a numpy array



In [ ]:
# 2 Dimension Array
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_row = two_dimension_array[0]
second_row = two_dimension_array[1]
third_row = two_dimension_array[2]
print('First row:', first_row)
print('Second row:', second_row)
print('Third row: ', third_row)

In [ ]:
first_column= two_dimension_array[:,0]
second_column = two_dimension_array[:,1]
third_column = two_dimension_array[:,2]
print('First column:', first_column)
print('Second column:', second_column)
print('Third column: ', third_column)
print(two_dimension_array)


## Slicing Numpy array

Slicing in numpy is similar to slicing in python list



In [ ]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_two_rows_and_columns = two_dimension_array[0:2, 0:2]
print(first_two_rows_and_columns)

How to reverse the rows and the whole array?



In [ ]:
two_dimension_array[::]

## Reverse the row and column positions



In [ ]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
two_dimension_array[::-1,::-1]

## How to represent missing values ?



In [ ]:
print(two_dimension_array)
two_dimension_array[1,1] = 55
two_dimension_array[1,2] =44
print(two_dimension_array)

In [ ]:
# Numpy Zeroes
# numpy.zeros(shape, dtype=float, order='C')
numpy_zeroes = np.zeros((3,3),dtype=int,order='C')
numpy_zeroes

In [ ]:
# Reshape
# numpy.reshape(), numpy.flatten()
first_shape  = np.array([(1,2,3), (4,5,6)])
print(first_shape)
reshaped = first_shape.reshape(3,2)
print(reshaped)


In [ ]:
flattened = reshaped.flatten()
flattened

In [ ]:
## Horitzontal Stack
np_list_one = np.array([1,2,3])
np_list_two = np.array([4,5,6])

print(np_list_one + np_list_two)

print('Horizontal Append:', np.hstack((np_list_one, np_list_two)))

In [ ]:
## Vertical Stack
print('Vertical Append:', np.vstack((np_list_one, np_list_two)))

## Generating Random Numbers



In [ ]:
# Generate a random float  number
random_float = np.random.random()
random_float

In [ ]:
# Generate a random float  number
random_floats = np.random.random(5)
random_floats

In [ ]:
# Generating a random integers between 0 and 10

random_int = np.random.randint(0, 11)
random_int

In [ ]:
# Generating a random integers between 2 and 11, and creating a one row array
random_int = np.random.randint(2,10, size=4)
random_int

In [ ]:
# Generating a random integers between 0 and 10
random_int = np.random.randint(2,10, size=(3,3))
random_int

## Generationg random numbers



In [ ]:
# np.random.normal(mu, sigma, size)
normal_array = np.random.normal(79, 15, 80)
normal_array


# Numpy and Statistics

NumPy has quite useful statistical functions for finding minimum, maximum, mean, median, percentile,standard deviation and variance, etc from the given elements in the array. The functions are explained as follows − Statistical function Numpy is equipped with the robust statistical function as listed below

-- Numpy Functions: 
* Min np.min()
* Max np.max()
* Mean np.mean()
* Median np.median()
* Varience
* Percentile
* Standard deviation np.std()

In [ ]:
np_normal_dis = np.random.normal(5, 0.5, 100)
np_normal_dis
## min, max, mean, median, sd
print('min: ', two_dimension_array.min())
print('max: ', two_dimension_array.max())
print('mean: ',two_dimension_array.mean())
# print('median: ', two_dimension_array.median())
print('sd: ', two_dimension_array.std())

In [ ]:
print(two_dimension_array)
print('Column with minimum: ', np.amin(two_dimension_array,axis=0))
print('Column with maximum: ', np.amax(two_dimension_array,axis=0))
print('=== Row ==')
print('Row with minimum: ', np.amin(two_dimension_array,axis=1))
print('Row with maximum: ', np.amax(two_dimension_array,axis=1))

## How to create repeating sequences?



In [ ]:
a = [1,2,3]

# Repeat whole of 'a' two times
print('Tile:   ', np.tile(a, 2))

# Repeat each element of 'a' two times
print('Repeat: ', np.repeat(a, 2))


## How to generate random numbers?



In [ ]:
# One random number between [0,1)
one_random_num = np.random.random()
one_random_in = np.random
print(one_random_num)

In [ ]:
# Random numbers between [0,1) of shape 2,3
r = np.random.random(size=[2,3])
print(r)

In [ ]:
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))

In [ ]:
## Random numbers between [0, 1] of shape 2, 2
rand = np.random.rand(2,2)
rand

In [ ]:
# Random integers between [0, 10) of shape 2,5
rand_int = np.random.randint(0, 10, size=[5,3])
rand_int

## Linear Algebra
1. Dot Product



In [ ]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2,3])
g = np.array([4,5,3])
### 1*4+2*5 + 3*6
np.dot(f, g)  # 23

## NumPy Matrix Multiplication with np.matmul()



In [ ]:
### Matmul: matruc product of two arrays
h = [[1,2],[3,4]]
i = [[5,6],[7,8]]
### 1*5+2*7 = 19
np.matmul(h, i)

We use linear equation for quantities which have linear relationship. Let's see the example below:



In [ ]:
temp = np.array([1,2,3,4,5])
pressure = temp * 2 + 5
pressure

## Other Functions : These Fucnctions like List's functions

In [2]:
## 1- split array : Use to split the array into indviual arrays based on
vars=np.array([1,2,3,4,5,6,7,8,9])
co =np.array_split(vars,3)
print(co)


## 2- Search 

sea = np.array([1,2,3,4,3,5,6,8,4,5,6])
x = np.where(sea == 3)
print(x)


## 3- Sort 
srt = np.array([1,2,3,4,3,5,6,8,4,5,6])
print(np.sort(srt))

## Insert 

isrt = np.array([1,2,3,4])
x = np.insert(isrt,3,40)
print(x)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


## Refernces 
1. https://drive.google.com/file/d/1-An-5WBuqHxQsXmfhHFaIwXK4jBdcUUh/view?usp=sharing 
2. https://drive.google.com/file/d/1axigfUPuQoN3Uf_VZXXxLdmpMGeKOQpm/view?usp=sharing 